spring:
  profiles:
    active: @profileActive@
  application:
    name: ${project.artifactId}
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8

logging:
  config: classpath:config/logback.xml


dlmq:
  registry:
    enable: false
    namespace: io-sdmq
    serverList: 127.0.0.1:2181
  rqueue:
    cluster: false
    name: dq
    bucketSize: 4